# Config file for building MapThing
language: cpp
dist: trusty

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "bTvPKAEEms+9mUQxffpqdd8s5D5Nvtnxt4jgFepN1yQ4dKp0P9uWd0vKBwPQ/Ve9W9Xb0xs5PkJIAX40vhF6dGPJIvH+Koa84RTfE6pK1INnXmmpdemg/EXrZNKq5nuPN5vGpwIynWA57xFDXwe1b3t+h9F5Vvjzc+xhi3ikB8DmzEY3AfYCqeScGR6WJAzWcpMTWUwvYsmfEHT7DuJV3fQ8ft63uCKh+6CljDi0MTlRII8g5ENmdEDU/kKduc0B2Hi1AIECsKLyWnFj4RTSFMznCMB2zpJal9tf6NLn3qR3bmgvJz2QP/6l+92oTGNM68xKfuVZSLFchyMF8RcSUw1bjn5OI67SskHvyUIdtJe4+IswFe4M6srutPRbo+1tpzh7G5k5vgUTZcvsxtQRf5H4YeqAXQEEBpExZL8saWY09wA+0qctzLgws4dVWaaTDd6s/Baoa1BhxUXx4xdDrVJDUVqzeEY/dSDIamehIuj4JrRN+sx6SnNnjsh5LcwC6CTcSLHgmbbozWr19dbix/rGilWmtOoikcp2sxeE/YI6DF6MHzkfUW849PCHLiXLwr38SfJHaY67+/Qb/IERnLq9ArWAZXWSr9DWXAgpRz5nVRdo3lTnd7P9uZNvZMCHziyMzKEtPP6TFxHtBMvlB4sCFuDlQd6zQruh7yADwL4="

compiler:
  - clang
  - gcc
  
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo apt-get install --assume-yes -qq qt5-default qt5-qmake qtbase5-dev-tools libqt5svg5-dev qttools5-dev qtscript5-dev libqt5webkit5-dev nodejs npm
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo npm install
  - sudo npm install -g grunt

addons:
  coverity_scan:
    # GitHub project metadata
    # ** specific to your project **
    project:
      name: JamesRamm/MapThing
      version: 1.0
      description: MapThing

    # Where email notification of build analysis results will be sent
    notification_email: jamessramm@gmail.com

    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: cmake CMakeLists.txt

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make -j4

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: master

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make -j4

