# Config file for building MapThing
dist: trusty
language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
      - xvfb

before_install:
  - npm install -g electron-prebuilt
  - npm install

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

