environment: 
    QTDIR: 'C:\Qt\5.7\msvc2013_64'
    PATH: '%QTDIR%;%PATH%'
os: Visual Studio 2013
build_script:
    - cmake -G "Visual Studio 12 2013 Win64" "-DCMAKE_PREFIX_PATH=%QTDIR%"
    - cmake --build . --config Debug
